FROM node:20-alpine

ARG CACHE_BUST=1

WORKDIR /app

COPY dist ./dist
COPY dist-server ./dist-server
COPY server.js ./
COPY package*.json ./

RUN npm ci --only=production

EXPOSE 3000

CMD ["node", "server.js"]