ALTER TABLE "Lead" ALTER COLUMN "manager" TYPE TEXT COLLATE "ru-RU-x-icu";
ALTER TABLE "Lead" ALTER COLUMN "city" TYPE TEXT COLLATE "ru-RU-x-icu";
ALTER TABLE "Lead" ALTER COLUMN "industry" TYPE TEXT COLLATE "ru-RU-x-icu";
ALTER TABLE "Lead" ALTER COLUMN "company" TYPE TEXT COLLATE "ru-RU-x-icu";
ALTER TABLE "Lead" ALTER COLUMN "firstName" TYPE TEXT COLLATE "ru-RU-x-icu";
ALTER TABLE "Lead" ALTER COLUMN "lastName" TYPE TEXT COLLATE "ru-RU-x-icu";
ALTER TABLE "Lead" ALTER COLUMN "position" TYPE TEXT COLLATE "ru-RU-x-icu";